from fastapi import FastAPI, HTTPException
from models.schema import SkillResponse
from core.config_manager import LLMConfig, load_config, save_config
from agents.workflow import skill_agent_app  # 引入我们写好的 LangGraph 图
from agents.state import AgentState
from typing import List
from sqlalchemy.orm import Session
from fastapi import Depends
from models.database import SessionLocal, SkillRecord

# 依赖项：获取数据库会话
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


app = FastAPI(
    title="SkillCraft AI Backend",
    description="Godot 组件生成引擎与 API 大厅",
    version="0.1.0",
)

@app.get("/")
async def read_root() -> dict[str, str]:
    return {"message": "Welcome to SkillCraft AI Backend"}

@app.get("/health")
async def health_check() -> dict[str, str]:
    return {"status": "ok"}

# ==========================================
# 系统配置接口 (用于前端配置 DeepSeek 密钥)
# ==========================================
@app.get("/api/v1/config", response_model=LLMConfig)
async def get_system_config():
    return load_config()

@app.post("/api/v1/config")
async def update_system_config(config: LLMConfig):
    save_config(config)
    return {"status": "success", "message": "系统配置已保存到 config.json"}

# ==========================================
# 核心业务接口：AI 组件生成
# ==========================================
@app.post("/api/v1/skills/generate", response_model=SkillResponse)
async def generate_skill(prompt: str):
    """
    输入自然语言需求，通过 LangGraph Agent 自动化生成 Godot 代码组件。
    """
    initial_state: AgentState = {
        "user_prompt": prompt,
        "sop_content": "",      
        "generated_code": None,
        "parsed_params": None,
        "skill_name": None,
        "description": None,
        "error": None,
        "iteration_count": 0,
        "feedback": None,
        "is_valid": False
    }
    
    # 2. 运行 Agent 工作流
    try:
        final_state = skill_agent_app.invoke(initial_state)
    except Exception as e:
        # 如果你能在终端里看到具体打印的错误，其实就是在这捕获的
        print(f"LangGraph 崩溃详情: {e}") 
        raise HTTPException(status_code=500, detail=f"Agent 运行异常: {str(e)}")
    
    if final_state.get("error"):
        raise HTTPException(status_code=400, detail=final_state["error"])
        
    return SkillResponse(
        id=f"skill_{abs(hash(prompt)) % 10000:04d}",
        name=final_state.get("skill_name", "GeneratedSkill"),
        alias_zh=final_state.get("alias_zh", "未命名组件"),
        category=final_state.get("category", "System"),
        description=final_state.get("description", "Auto-generated by SkillCraft AI"),
        code_content=final_state.get("generated_code", ""),
        export_params=final_state.get("parsed_params", {}),
        author="SkillCraft AI Agent"
    )

# ==========================================
# 资产库接口 (Data Layer)
# ==========================================
@app.post("/api/v1/library/skills")
async def save_skill_to_library(skill_data: dict, db: Session = Depends(get_db)):
    """将生成的组件正式存入本地资产库"""
    new_skill = SkillRecord(
        name=skill_data.get("name"),
        alias_zh=skill_data.get("alias_zh", "未命名组件"),
        category=skill_data.get("category", "System"),
        description=skill_data.get("description"),
        code_content=skill_data.get("code_content"),
        export_params=skill_data.get("export_params", {})
    )
    db.add(new_skill)
    db.commit()
    db.refresh(new_skill)
    return {"status": "success", "message": f"组件 {new_skill.alias_zh} 已入库！", "id": new_skill.id}

@app.get("/api/v1/library/skills")
async def get_skill_library(category: str = None, db: Session = Depends(get_db)):
    """获取本地资产库列表，支持按分类筛选"""
    query = db.query(SkillRecord)
    if category:
        query = query.filter(SkillRecord.category == category)
    
    skills = query.order_by(SkillRecord.created_at.desc()).all()
    # 返回精简信息用于列表展示
    return [
        {
            "id": s.id,
            "name": s.name,
            "alias_zh": s.alias_zh,
            "category": s.category,
            "cloud_synced": s.is_synced
        } for s in skills
    ]

@app.delete("/api/v1/library/skills/{skill_id}")
async def delete_skill_from_library(skill_id: str, db: Session = Depends(get_db)):
    """从本地资产库中删除指定组件"""
    skill = db.query(SkillRecord).filter(SkillRecord.id == skill_id).first()
    if not skill:
        raise HTTPException(status_code=404, detail="未找到该组件")
    
    db.delete(skill)
    db.commit()
    return {"status": "success", "message": "组件已删除"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)